### ISSUE TITLE
Is there any chance of using the radium-grid standalone ?

### ISSUE THREAD

**Issue by Roobyx** [FormidableLabs/radium-grid#75]
I really love the grid and I would love using it more, but I am not so keen on the Radium way of styling and all the "fuss". 

So is it possible to use the grid without "Radium" and most of all without <StyleRoot> etc. 

If not, you should mention "Radium" as a dependency for the grid in the Readme, since the user has to find that out after not being able to run the grid as is.

**Comment by ryan-roemer** [comment]
Radium is a hard dependency (hence **`radium`**`-grid` 😄 ), but we left it out of `peerDependencies` originally because of some of the logistics in varying npm versions.

You're welcome to open a PR with even more discussion of Radium being the core / required for Radium Grid if the README isn't sufficient for your present understanding. Thanks!
